### ISSUE TITLE
Windows上多机多卡时报 Socket timeout

### ISSUE THREAD

**Issue by Linxu59** [Lisennlp/distributed_train_pytorch#2]
您好，我在windows上运行您的代码，我是两台机器，每台机器一个显卡，运行时会报以下错误（我把代码中的后端改成gloo了，因为在windows上不支持nccl）。想请教下您有在windows上试过pytorch的多机多卡训练吗？
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    world_size = args.world_size
  File "D:\Software\Anaconda3\envs\torch18\lib\site-packages\torch\distributed\distributed_c10d.py", line 510, in init_process_group
    timeout=timeout))
  File "D:\Software\Anaconda3\envs\torch18\lib\site-packages\torch\distributed\distributed_c10d.py", line 592, in _new_process_group_helper
    timeout=timeout)
RuntimeError: Socket Timeout

**Comment by Lisennlp** [comment]
没有呢，我好多年没用Windows了，我也不太了解Windows电脑

**Comment by Linxu59** [comment]
> 

好的，谢谢您的回复。那如果在Linux上的话，是不是只要两台机器可以ping的通就可以做多机训练呢

**Comment by Lisennlp** [comment]
嗯是的，能ping通是基础条件
