### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by oshindow** [Lisennlp/distributed_train_pytorch#3]
启动时 second node 在初始化模型 net.cuda() 时报错 RuntimeError: CUDA error: out of memory 是为什么呢，master node 可以顺利加载模型，master node 和second node  都是4卡32G机器，second node没有GPU运行程序，也没有看到显存过大，大概占到600M。

torch 都是1.8.1 ，cuda 都是11.0
train.sh
```shell
# m每台机器使用显卡数目
nproc_per_node=2
# 主机器ip
MASTER_ADDR=112.126.74.110
# 主机器端口号，可以随意，只要不冲突
MASTER_PORT=29507
# 机器编号，主机器必须为0
node_rank=$1
# 使用的机器数量
nnodes=$2
# 每个进程的线程数目
# export OMP_NUM_THREADS=3
# 训练命令
DISTRIBUTED_ARGS="--nproc_per_node $nproc_per_node --node_rank $node_rank --nnodes $nnodes --master_addr $MASTER_ADDR --master_port $MASTER_PORT"
CUDA_VISIBLE_DEVICES=2,3 python3 -W ignore -m torch.distributed.launch $DISTRIBUTED_ARGS main.py
```
master node：
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
global_rank = 1 local_rank = 1 world_size = 4
global_rank = 0 local_rank = 0 world_size = 4
```
second node：
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
global_rank = 3 local_rank = 1 world_size = 4
global_rank = 2 local_rank = 0 world_size = 4
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    net.cuda()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
```

**Comment by oshindow** [comment]
可能是机器硬件问题
